//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginInsViviendas_UNO.soaFracc {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://esb.javer.com/CatFraccionamientos", ConfigurationName="soaFracc.CatFraccionamientosPortType")]
    public interface CatFraccionamientosPortType {
        
        // CODEGEN: Generating message contract since the operation GetFraccionamientosByUserAndRight is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetFraccionamientosByUserAndRight", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestType))]
        PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightResponse GetFraccionamientosByUserAndRight(PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightRequest request);
        
        // CODEGEN: Generating message contract since the operation GetFraccionamientos is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetFraccionamientos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestType))]
        PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightResponse GetFraccionamientos(PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esb.javer.com/CatFraccionamientos/types")]
    public partial class GetFraccionamientosRq : RequestType {
        
        private string usernameField;
        
        private string requestedAccessField;
        
        private string iP_AddressField;
        
        private string queryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestedAccess {
            get {
                return this.requestedAccessField;
            }
            set {
                this.requestedAccessField = value;
                this.RaisePropertyChanged("RequestedAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IP_Address {
            get {
                return this.iP_AddressField;
            }
            set {
                this.iP_AddressField = value;
                this.RaisePropertyChanged("IP_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string QueryType {
            get {
                return this.queryTypeField;
            }
            set {
                this.queryTypeField = value;
                this.RaisePropertyChanged("QueryType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class RequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private System.DateTime requestDateField;
        
        private bool requestDateFieldSpecified;
        
        private string sourceSystemField;
        
        private string transactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestDateSpecified {
            get {
                return this.requestDateFieldSpecified;
            }
            set {
                this.requestDateFieldSpecified = value;
                this.RaisePropertyChanged("RequestDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceSystem {
            get {
                return this.sourceSystemField;
            }
            set {
                this.sourceSystemField = value;
                this.RaisePropertyChanged("SourceSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class FideicomisoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string descriptionField;
        
        private string estatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Description {
            get {
                return this.descriptionField;
            }
            set {
                this.descriptionField = value;
                this.RaisePropertyChanged("Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("Estatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class HomeType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string pisoField;
        
        private string manzanaField;
        
        private string numeroLoteField;
        
        private string numeroInteriorField;
        
        private string unidadPrivativaField;
        
        private string direccionField;
        
        private string numeroOficialField;
        
        private string m2SuperficieField;
        
        private string m2ConstruccionField;
        
        private string m2SuperficieExcedenteField;
        
        private string superfloteTipoField;
        
        private string avanceObraFisicoField;
        
        private string avanceObraFinancieroField;
        
        private string anioProgramaField;
        
        private string paqueteInfonavitField;
        
        private string cveUnicaViviendaField;
        
        private string rUVField;
        
        private string cablevisionField;
        
        private string nuevaManzanaField;
        
        private string nuevoLoteField;
        
        private string nuevoNumeroIntField;
        
        private string esquinaField;
        
        private string ladoSolField;
        
        private string ladoSombraField;
        
        private string motivoBajaField;
        
        private string razonCambioField;
        
        private string numeroInternoField;
        
        private string formalizacionContadoField;
        
        private string nuevaUnidadPrivativaField;
        
        private string flagUnidadPrivativaField;
        
        private string flagDTUField;
        
        private string flagDTIField;
        
        private string flagMuestraField;
        
        private string flagDisponibleField;
        
        private string flagFrenteParqueField;
        
        private string flagSobreAvenidaField;
        
        private string flagNuevaUnidadPrivativaField;
        
        private string flagGravamenField;
        
        private string flagViviendaVerdeField;
        
        private string fechaAvanceField;
        
        private string fechaAvaluoField;
        
        private string fechaVigenciaPredialField;
        
        private string fechaDTUField;
        
        private string fechaDTIField;
        
        private string fechaLiberacionGravamenField;
        
        private string prototipoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Piso {
            get {
                return this.pisoField;
            }
            set {
                this.pisoField = value;
                this.RaisePropertyChanged("Piso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Manzana {
            get {
                return this.manzanaField;
            }
            set {
                this.manzanaField = value;
                this.RaisePropertyChanged("Manzana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("NumeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroInterior {
            get {
                return this.numeroInteriorField;
            }
            set {
                this.numeroInteriorField = value;
                this.RaisePropertyChanged("NumeroInterior");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string UnidadPrivativa {
            get {
                return this.unidadPrivativaField;
            }
            set {
                this.unidadPrivativaField = value;
                this.RaisePropertyChanged("UnidadPrivativa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("Direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroOficial {
            get {
                return this.numeroOficialField;
            }
            set {
                this.numeroOficialField = value;
                this.RaisePropertyChanged("NumeroOficial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string M2Superficie {
            get {
                return this.m2SuperficieField;
            }
            set {
                this.m2SuperficieField = value;
                this.RaisePropertyChanged("M2Superficie");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string M2Construccion {
            get {
                return this.m2ConstruccionField;
            }
            set {
                this.m2ConstruccionField = value;
                this.RaisePropertyChanged("M2Construccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string M2SuperficieExcedente {
            get {
                return this.m2SuperficieExcedenteField;
            }
            set {
                this.m2SuperficieExcedenteField = value;
                this.RaisePropertyChanged("M2SuperficieExcedente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SuperfloteTipo {
            get {
                return this.superfloteTipoField;
            }
            set {
                this.superfloteTipoField = value;
                this.RaisePropertyChanged("SuperfloteTipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AvanceObraFisico {
            get {
                return this.avanceObraFisicoField;
            }
            set {
                this.avanceObraFisicoField = value;
                this.RaisePropertyChanged("AvanceObraFisico");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AvanceObraFinanciero {
            get {
                return this.avanceObraFinancieroField;
            }
            set {
                this.avanceObraFinancieroField = value;
                this.RaisePropertyChanged("AvanceObraFinanciero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string AnioPrograma {
            get {
                return this.anioProgramaField;
            }
            set {
                this.anioProgramaField = value;
                this.RaisePropertyChanged("AnioPrograma");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string PaqueteInfonavit {
            get {
                return this.paqueteInfonavitField;
            }
            set {
                this.paqueteInfonavitField = value;
                this.RaisePropertyChanged("PaqueteInfonavit");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string CveUnicaVivienda {
            get {
                return this.cveUnicaViviendaField;
            }
            set {
                this.cveUnicaViviendaField = value;
                this.RaisePropertyChanged("CveUnicaVivienda");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RUV {
            get {
                return this.rUVField;
            }
            set {
                this.rUVField = value;
                this.RaisePropertyChanged("RUV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Cablevision {
            get {
                return this.cablevisionField;
            }
            set {
                this.cablevisionField = value;
                this.RaisePropertyChanged("Cablevision");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NuevaManzana {
            get {
                return this.nuevaManzanaField;
            }
            set {
                this.nuevaManzanaField = value;
                this.RaisePropertyChanged("NuevaManzana");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NuevoLote {
            get {
                return this.nuevoLoteField;
            }
            set {
                this.nuevoLoteField = value;
                this.RaisePropertyChanged("NuevoLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NuevoNumeroInt {
            get {
                return this.nuevoNumeroIntField;
            }
            set {
                this.nuevoNumeroIntField = value;
                this.RaisePropertyChanged("NuevoNumeroInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Esquina {
            get {
                return this.esquinaField;
            }
            set {
                this.esquinaField = value;
                this.RaisePropertyChanged("Esquina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LadoSol {
            get {
                return this.ladoSolField;
            }
            set {
                this.ladoSolField = value;
                this.RaisePropertyChanged("LadoSol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string LadoSombra {
            get {
                return this.ladoSombraField;
            }
            set {
                this.ladoSombraField = value;
                this.RaisePropertyChanged("LadoSombra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MotivoBaja {
            get {
                return this.motivoBajaField;
            }
            set {
                this.motivoBajaField = value;
                this.RaisePropertyChanged("MotivoBaja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RazonCambio {
            get {
                return this.razonCambioField;
            }
            set {
                this.razonCambioField = value;
                this.RaisePropertyChanged("RazonCambio");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NumeroInterno {
            get {
                return this.numeroInternoField;
            }
            set {
                this.numeroInternoField = value;
                this.RaisePropertyChanged("NumeroInterno");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FormalizacionContado {
            get {
                return this.formalizacionContadoField;
            }
            set {
                this.formalizacionContadoField = value;
                this.RaisePropertyChanged("FormalizacionContado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NuevaUnidadPrivativa {
            get {
                return this.nuevaUnidadPrivativaField;
            }
            set {
                this.nuevaUnidadPrivativaField = value;
                this.RaisePropertyChanged("NuevaUnidadPrivativa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlagUnidadPrivativa {
            get {
                return this.flagUnidadPrivativaField;
            }
            set {
                this.flagUnidadPrivativaField = value;
                this.RaisePropertyChanged("FlagUnidadPrivativa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlagDTU {
            get {
                return this.flagDTUField;
            }
            set {
                this.flagDTUField = value;
                this.RaisePropertyChanged("FlagDTU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlagDTI {
            get {
                return this.flagDTIField;
            }
            set {
                this.flagDTIField = value;
                this.RaisePropertyChanged("FlagDTI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlagMuestra {
            get {
                return this.flagMuestraField;
            }
            set {
                this.flagMuestraField = value;
                this.RaisePropertyChanged("FlagMuestra");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlagDisponible {
            get {
                return this.flagDisponibleField;
            }
            set {
                this.flagDisponibleField = value;
                this.RaisePropertyChanged("FlagDisponible");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlagFrenteParque {
            get {
                return this.flagFrenteParqueField;
            }
            set {
                this.flagFrenteParqueField = value;
                this.RaisePropertyChanged("FlagFrenteParque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlagSobreAvenida {
            get {
                return this.flagSobreAvenidaField;
            }
            set {
                this.flagSobreAvenidaField = value;
                this.RaisePropertyChanged("FlagSobreAvenida");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlagNuevaUnidadPrivativa {
            get {
                return this.flagNuevaUnidadPrivativaField;
            }
            set {
                this.flagNuevaUnidadPrivativaField = value;
                this.RaisePropertyChanged("FlagNuevaUnidadPrivativa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlagGravamen {
            get {
                return this.flagGravamenField;
            }
            set {
                this.flagGravamenField = value;
                this.RaisePropertyChanged("FlagGravamen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FlagViviendaVerde {
            get {
                return this.flagViviendaVerdeField;
            }
            set {
                this.flagViviendaVerdeField = value;
                this.RaisePropertyChanged("FlagViviendaVerde");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaAvance {
            get {
                return this.fechaAvanceField;
            }
            set {
                this.fechaAvanceField = value;
                this.RaisePropertyChanged("FechaAvance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaAvaluo {
            get {
                return this.fechaAvaluoField;
            }
            set {
                this.fechaAvaluoField = value;
                this.RaisePropertyChanged("FechaAvaluo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaVigenciaPredial {
            get {
                return this.fechaVigenciaPredialField;
            }
            set {
                this.fechaVigenciaPredialField = value;
                this.RaisePropertyChanged("FechaVigenciaPredial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaDTU {
            get {
                return this.fechaDTUField;
            }
            set {
                this.fechaDTUField = value;
                this.RaisePropertyChanged("FechaDTU");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaDTI {
            get {
                return this.fechaDTIField;
            }
            set {
                this.fechaDTIField = value;
                this.RaisePropertyChanged("FechaDTI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string FechaLiberacionGravamen {
            get {
                return this.fechaLiberacionGravamenField;
            }
            set {
                this.fechaLiberacionGravamenField = value;
                this.RaisePropertyChanged("FechaLiberacionGravamen");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Prototipo {
            get {
                return this.prototipoField;
            }
            set {
                this.prototipoField = value;
                this.RaisePropertyChanged("Prototipo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class HomeListType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HomeType[] homeField;
        
        private int itemQuantityField;
        
        private bool itemQuantityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Home", Order=0)]
        public HomeType[] Home {
            get {
                return this.homeField;
            }
            set {
                this.homeField = value;
                this.RaisePropertyChanged("Home");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ItemQuantity {
            get {
                return this.itemQuantityField;
            }
            set {
                this.itemQuantityField = value;
                this.RaisePropertyChanged("ItemQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemQuantitySpecified {
            get {
                return this.itemQuantityFieldSpecified;
            }
            set {
                this.itemQuantityFieldSpecified = value;
                this.RaisePropertyChanged("ItemQuantitySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class ConjuntoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HomeListType homeListField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string homeQuantityField;
        
        private string homePendingQuantityField;
        
        private string homeRegisteredQuantityField;
        
        private string estatusField;
        
        private string prototipoField;
        
        private string isNewFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public HomeListType HomeList {
            get {
                return this.homeListField;
            }
            set {
                this.homeListField = value;
                this.RaisePropertyChanged("HomeList");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HomeQuantity {
            get {
                return this.homeQuantityField;
            }
            set {
                this.homeQuantityField = value;
                this.RaisePropertyChanged("HomeQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HomePendingQuantity {
            get {
                return this.homePendingQuantityField;
            }
            set {
                this.homePendingQuantityField = value;
                this.RaisePropertyChanged("HomePendingQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string HomeRegisteredQuantity {
            get {
                return this.homeRegisteredQuantityField;
            }
            set {
                this.homeRegisteredQuantityField = value;
                this.RaisePropertyChanged("HomeRegisteredQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("Estatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Prototipo {
            get {
                return this.prototipoField;
            }
            set {
                this.prototipoField = value;
                this.RaisePropertyChanged("Prototipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsNewFlag {
            get {
                return this.isNewFlagField;
            }
            set {
                this.isNewFlagField = value;
                this.RaisePropertyChanged("IsNewFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class ConjuntoListType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConjuntoType[] conjuntoField;
        
        private int itemQuantityField;
        
        private bool itemQuantityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Conjunto", Order=0)]
        public ConjuntoType[] Conjunto {
            get {
                return this.conjuntoField;
            }
            set {
                this.conjuntoField = value;
                this.RaisePropertyChanged("Conjunto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ItemQuantity {
            get {
                return this.itemQuantityField;
            }
            set {
                this.itemQuantityField = value;
                this.RaisePropertyChanged("ItemQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemQuantitySpecified {
            get {
                return this.itemQuantityFieldSpecified;
            }
            set {
                this.itemQuantityFieldSpecified = value;
                this.RaisePropertyChanged("ItemQuantitySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class FrenteType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ConjuntoListType conjuntosField;
        
        private FideicomisoType fideicomisoField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string codeField;
        
        private string estatusField;
        
        private bool fideicomisoFlagField;
        
        private bool fideicomisoFlagFieldSpecified;
        
        private string isNewFlagField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ConjuntoListType Conjuntos {
            get {
                return this.conjuntosField;
            }
            set {
                this.conjuntosField = value;
                this.RaisePropertyChanged("Conjuntos");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public FideicomisoType Fideicomiso {
            get {
                return this.fideicomisoField;
            }
            set {
                this.fideicomisoField = value;
                this.RaisePropertyChanged("Fideicomiso");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("Estatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool FideicomisoFlag {
            get {
                return this.fideicomisoFlagField;
            }
            set {
                this.fideicomisoFlagField = value;
                this.RaisePropertyChanged("FideicomisoFlag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FideicomisoFlagSpecified {
            get {
                return this.fideicomisoFlagFieldSpecified;
            }
            set {
                this.fideicomisoFlagFieldSpecified = value;
                this.RaisePropertyChanged("FideicomisoFlagSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string IsNewFlag {
            get {
                return this.isNewFlagField;
            }
            set {
                this.isNewFlagField = value;
                this.RaisePropertyChanged("IsNewFlag");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class FrenteListType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrenteType[] frenteField;
        
        private int itemQuantityField;
        
        private bool itemQuantityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Frente", Order=0)]
        public FrenteType[] Frente {
            get {
                return this.frenteField;
            }
            set {
                this.frenteField = value;
                this.RaisePropertyChanged("Frente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ItemQuantity {
            get {
                return this.itemQuantityField;
            }
            set {
                this.itemQuantityField = value;
                this.RaisePropertyChanged("ItemQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemQuantitySpecified {
            get {
                return this.itemQuantityFieldSpecified;
            }
            set {
                this.itemQuantityFieldSpecified = value;
                this.RaisePropertyChanged("ItemQuantitySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class FraccionamientoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FrenteListType frentesField;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string codeField;
        
        private string estatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FrenteListType Frentes {
            get {
                return this.frentesField;
            }
            set {
                this.frentesField = value;
                this.RaisePropertyChanged("Frentes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("Estatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class FraccionamientoListType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private FraccionamientoType[] fraccionamientoField;
        
        private int itemQuantityField;
        
        private bool itemQuantityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Fraccionamiento", Order=0)]
        public FraccionamientoType[] Fraccionamiento {
            get {
                return this.fraccionamientoField;
            }
            set {
                this.fraccionamientoField = value;
                this.RaisePropertyChanged("Fraccionamiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ItemQuantity {
            get {
                return this.itemQuantityField;
            }
            set {
                this.itemQuantityField = value;
                this.RaisePropertyChanged("ItemQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemQuantitySpecified {
            get {
                return this.itemQuantityFieldSpecified;
            }
            set {
                this.itemQuantityFieldSpecified = value;
                this.RaisePropertyChanged("ItemQuantitySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class ErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string languageField;
        
        private string typeField;
        
        private string shortTextField;
        
        private string codeField;
        
        private string docURLField;
        
        private string statusField;
        
        private string tagField;
        
        private string recordIDField;
        
        private string nodeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShortText {
            get {
                return this.shortTextField;
            }
            set {
                this.shortTextField = value;
                this.RaisePropertyChanged("ShortText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DocURL {
            get {
                return this.docURLField;
            }
            set {
                this.docURLField = value;
                this.RaisePropertyChanged("DocURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
                this.RaisePropertyChanged("RecordID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NodeList {
            get {
                return this.nodeListField;
            }
            set {
                this.nodeListField = value;
                this.RaisePropertyChanged("NodeList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class ResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorType errorField;
        
        private System.DateTime responseDateField;
        
        private bool responseDateFieldSpecified;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private string eSB_IdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorType Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ResponseDate {
            get {
                return this.responseDateField;
            }
            set {
                this.responseDateField = value;
                this.RaisePropertyChanged("ResponseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseDateSpecified {
            get {
                return this.responseDateFieldSpecified;
            }
            set {
                this.responseDateFieldSpecified = value;
                this.RaisePropertyChanged("ResponseDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("SuccessSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ESB_Id {
            get {
                return this.eSB_IdField;
            }
            set {
                this.eSB_IdField = value;
                this.RaisePropertyChanged("ESB_Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esb.javer.com/CatFraccionamientos/types")]
    public partial class GetFraccionamientosRs : ResponseType {
        
        private FraccionamientoListType fraccionamientosField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public FraccionamientoListType Fraccionamientos {
            get {
                return this.fraccionamientosField;
            }
            set {
                this.fraccionamientosField = value;
                this.RaisePropertyChanged("Fraccionamientos");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFraccionamientosByUserAndRightRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://esb.javer.com/CatFraccionamientos/types", Order=0)]
        public PluginInsViviendas_UNO.soaFracc.GetFraccionamientosRq GetFraccionamientosRq;
        
        public GetFraccionamientosByUserAndRightRequest() {
        }
        
        public GetFraccionamientosByUserAndRightRequest(PluginInsViviendas_UNO.soaFracc.GetFraccionamientosRq GetFraccionamientosRq) {
            this.GetFraccionamientosRq = GetFraccionamientosRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFraccionamientosByUserAndRightResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://esb.javer.com/CatFraccionamientos/types", Order=0)]
        public PluginInsViviendas_UNO.soaFracc.GetFraccionamientosRs GetFraccionamientosRs;
        
        public GetFraccionamientosByUserAndRightResponse() {
        }
        
        public GetFraccionamientosByUserAndRightResponse(PluginInsViviendas_UNO.soaFracc.GetFraccionamientosRs GetFraccionamientosRs) {
            this.GetFraccionamientosRs = GetFraccionamientosRs;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CatFraccionamientosPortTypeChannel : PluginInsViviendas_UNO.soaFracc.CatFraccionamientosPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatFraccionamientosPortTypeClient : System.ServiceModel.ClientBase<PluginInsViviendas_UNO.soaFracc.CatFraccionamientosPortType>, PluginInsViviendas_UNO.soaFracc.CatFraccionamientosPortType {
        
        public CatFraccionamientosPortTypeClient() {
        }
        
        public CatFraccionamientosPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatFraccionamientosPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatFraccionamientosPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatFraccionamientosPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightResponse PluginInsViviendas_UNO.soaFracc.CatFraccionamientosPortType.GetFraccionamientosByUserAndRight(PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightRequest request) {
            return base.Channel.GetFraccionamientosByUserAndRight(request);
        }
        
        public PluginInsViviendas_UNO.soaFracc.GetFraccionamientosRs GetFraccionamientosByUserAndRight(PluginInsViviendas_UNO.soaFracc.GetFraccionamientosRq GetFraccionamientosRq) {
            PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightRequest inValue = new PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightRequest();
            inValue.GetFraccionamientosRq = GetFraccionamientosRq;
            PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightResponse retVal = ((PluginInsViviendas_UNO.soaFracc.CatFraccionamientosPortType)(this)).GetFraccionamientosByUserAndRight(inValue);
            return retVal.GetFraccionamientosRs;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightResponse PluginInsViviendas_UNO.soaFracc.CatFraccionamientosPortType.GetFraccionamientos(PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightRequest request) {
            return base.Channel.GetFraccionamientos(request);
        }
        
        public PluginInsViviendas_UNO.soaFracc.GetFraccionamientosRs GetFraccionamientos(PluginInsViviendas_UNO.soaFracc.GetFraccionamientosRq GetFraccionamientosRq) {
            PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightRequest inValue = new PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightRequest();
            inValue.GetFraccionamientosRq = GetFraccionamientosRq;
            PluginInsViviendas_UNO.soaFracc.GetFraccionamientosByUserAndRightResponse retVal = ((PluginInsViviendas_UNO.soaFracc.CatFraccionamientosPortType)(this)).GetFraccionamientos(inValue);
            return retVal.GetFraccionamientosRs;
        }
    }
}
