//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginInsViviendas_UNO.soaPrototipos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://esb.javer.com/CatPrototipos", ConfigurationName="soaPrototipos.CatPrototiposPortType")]
    public interface CatPrototiposPortType {
        
        // CODEGEN: Generating message contract since the operation GetPrototipos is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="GetPrototipos", ReplyAction="*")]
        [System.ServiceModel.TransactionFlowAttribute(System.ServiceModel.TransactionFlowOption.Allowed)]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ResponseType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(RequestType))]
        PluginInsViviendas_UNO.soaPrototipos.GetPrototiposResponse GetPrototipos(PluginInsViviendas_UNO.soaPrototipos.GetPrototiposRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esb.javer.com/CatPrototipos/types")]
    public partial class GetPrototiposRq : RequestType {
        
        private string usernameField;
        
        private string requestedAccessField;
        
        private string iP_AddressField;
        
        private string queryTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Username {
            get {
                return this.usernameField;
            }
            set {
                this.usernameField = value;
                this.RaisePropertyChanged("Username");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestedAccess {
            get {
                return this.requestedAccessField;
            }
            set {
                this.requestedAccessField = value;
                this.RaisePropertyChanged("RequestedAccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string IP_Address {
            get {
                return this.iP_AddressField;
            }
            set {
                this.iP_AddressField = value;
                this.RaisePropertyChanged("IP_Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string QueryType {
            get {
                return this.queryTypeField;
            }
            set {
                this.queryTypeField = value;
                this.RaisePropertyChanged("QueryType");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class RequestType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string versionField;
        
        private System.DateTime requestDateField;
        
        private bool requestDateFieldSpecified;
        
        private string sourceSystemField;
        
        private string transactionIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Version {
            get {
                return this.versionField;
            }
            set {
                this.versionField = value;
                this.RaisePropertyChanged("Version");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime RequestDate {
            get {
                return this.requestDateField;
            }
            set {
                this.requestDateField = value;
                this.RaisePropertyChanged("RequestDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RequestDateSpecified {
            get {
                return this.requestDateFieldSpecified;
            }
            set {
                this.requestDateFieldSpecified = value;
                this.RaisePropertyChanged("RequestDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string SourceSystem {
            get {
                return this.sourceSystemField;
            }
            set {
                this.sourceSystemField = value;
                this.RaisePropertyChanged("SourceSystem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string TransactionID {
            get {
                return this.transactionIDField;
            }
            set {
                this.transactionIDField = value;
                this.RaisePropertyChanged("TransactionID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class PrototipoType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private string estatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("ID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("IDSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
                this.RaisePropertyChanged("Estatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class PrototipoListType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private PrototipoType[] prototipoField;
        
        private int itemQuantityField;
        
        private bool itemQuantityFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Prototipo", Order=0)]
        public PrototipoType[] Prototipo {
            get {
                return this.prototipoField;
            }
            set {
                this.prototipoField = value;
                this.RaisePropertyChanged("Prototipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public int ItemQuantity {
            get {
                return this.itemQuantityField;
            }
            set {
                this.itemQuantityField = value;
                this.RaisePropertyChanged("ItemQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ItemQuantitySpecified {
            get {
                return this.itemQuantityFieldSpecified;
            }
            set {
                this.itemQuantityFieldSpecified = value;
                this.RaisePropertyChanged("ItemQuantitySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class ErrorType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string languageField;
        
        private string typeField;
        
        private string shortTextField;
        
        private string codeField;
        
        private string docURLField;
        
        private string statusField;
        
        private string tagField;
        
        private string recordIDField;
        
        private string nodeListField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="language")]
        public string Language {
            get {
                return this.languageField;
            }
            set {
                this.languageField = value;
                this.RaisePropertyChanged("Language");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Type {
            get {
                return this.typeField;
            }
            set {
                this.typeField = value;
                this.RaisePropertyChanged("Type");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ShortText {
            get {
                return this.shortTextField;
            }
            set {
                this.shortTextField = value;
                this.RaisePropertyChanged("ShortText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string DocURL {
            get {
                return this.docURLField;
            }
            set {
                this.docURLField = value;
                this.RaisePropertyChanged("DocURL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string Tag {
            get {
                return this.tagField;
            }
            set {
                this.tagField = value;
                this.RaisePropertyChanged("Tag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string RecordID {
            get {
                return this.recordIDField;
            }
            set {
                this.recordIDField = value;
                this.RaisePropertyChanged("RecordID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string NodeList {
            get {
                return this.nodeListField;
            }
            set {
                this.nodeListField = value;
                this.RaisePropertyChanged("NodeList");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://esb.javer.com/common")]
    public partial class ResponseType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ErrorType errorField;
        
        private System.DateTime responseDateField;
        
        private bool responseDateFieldSpecified;
        
        private bool successField;
        
        private bool successFieldSpecified;
        
        private string eSB_IdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ErrorType Error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("Error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime ResponseDate {
            get {
                return this.responseDateField;
            }
            set {
                this.responseDateField = value;
                this.RaisePropertyChanged("ResponseDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ResponseDateSpecified {
            get {
                return this.responseDateFieldSpecified;
            }
            set {
                this.responseDateFieldSpecified = value;
                this.RaisePropertyChanged("ResponseDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool SuccessSpecified {
            get {
                return this.successFieldSpecified;
            }
            set {
                this.successFieldSpecified = value;
                this.RaisePropertyChanged("SuccessSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string ESB_Id {
            get {
                return this.eSB_IdField;
            }
            set {
                this.eSB_IdField = value;
                this.RaisePropertyChanged("ESB_Id");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2102.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://esb.javer.com/CatPrototipos/types")]
    public partial class GetPrototiposRs : ResponseType {
        
        private PrototipoListType prototiposField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PrototipoListType Prototipos {
            get {
                return this.prototiposField;
            }
            set {
                this.prototiposField = value;
                this.RaisePropertyChanged("Prototipos");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrototiposRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://esb.javer.com/CatPrototipos/types", Order=0)]
        public PluginInsViviendas_UNO.soaPrototipos.GetPrototiposRq GetPrototiposRq;
        
        public GetPrototiposRequest() {
        }
        
        public GetPrototiposRequest(PluginInsViviendas_UNO.soaPrototipos.GetPrototiposRq GetPrototiposRq) {
            this.GetPrototiposRq = GetPrototiposRq;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPrototiposResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://esb.javer.com/CatPrototipos/types", Order=0)]
        public PluginInsViviendas_UNO.soaPrototipos.GetPrototiposRs GetPrototiposRs;
        
        public GetPrototiposResponse() {
        }
        
        public GetPrototiposResponse(PluginInsViviendas_UNO.soaPrototipos.GetPrototiposRs GetPrototiposRs) {
            this.GetPrototiposRs = GetPrototiposRs;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CatPrototiposPortTypeChannel : PluginInsViviendas_UNO.soaPrototipos.CatPrototiposPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CatPrototiposPortTypeClient : System.ServiceModel.ClientBase<PluginInsViviendas_UNO.soaPrototipos.CatPrototiposPortType>, PluginInsViviendas_UNO.soaPrototipos.CatPrototiposPortType {
        
        public CatPrototiposPortTypeClient() {
        }
        
        public CatPrototiposPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CatPrototiposPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatPrototiposPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CatPrototiposPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        PluginInsViviendas_UNO.soaPrototipos.GetPrototiposResponse PluginInsViviendas_UNO.soaPrototipos.CatPrototiposPortType.GetPrototipos(PluginInsViviendas_UNO.soaPrototipos.GetPrototiposRequest request) {
            return base.Channel.GetPrototipos(request);
        }
        
        public PluginInsViviendas_UNO.soaPrototipos.GetPrototiposRs GetPrototipos(PluginInsViviendas_UNO.soaPrototipos.GetPrototiposRq GetPrototiposRq) {
            PluginInsViviendas_UNO.soaPrototipos.GetPrototiposRequest inValue = new PluginInsViviendas_UNO.soaPrototipos.GetPrototiposRequest();
            inValue.GetPrototiposRq = GetPrototiposRq;
            PluginInsViviendas_UNO.soaPrototipos.GetPrototiposResponse retVal = ((PluginInsViviendas_UNO.soaPrototipos.CatPrototiposPortType)(this)).GetPrototipos(inValue);
            return retVal.GetPrototiposRs;
        }
    }
}
